### ISSUE TITLE
Golang generate encounters the type error of appName

### ISSUE THREAD

**Issue by GeekEast** [kyoh86/generator-go-project#18]
+---------------------+
Golang project scaffold
+---------------------+

? name: myapp
? appVersion: 0.0.1
? description: Your project description
? user: xiangt
? **appPath: "app"**
? typeToGenerate: cli
events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: **The "path" argument must be of type string. Received type undefined**
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at module.exports.configuring (/Users/xiangt/node_modules/generator-golang-project/generators/app/index.js:124:44)
    at Object.<anonymous> (/Users/xiangt/node_modules/yeoman-generator/lib/index.js:647:25)
    at /Users/xiangt/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /Users/xiangt/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/Users/xiangt/node_modules/yeoman-generator/lib/index.js:648:11)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/xiangt/node_modules/yeoman-generator/lib/index.js:668:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

**Comment by kyoh86** [comment]
@GeekEast 
This is `generator-go-project` repository.
You're using `generator-golang-project`.
It's not my issue.
